// Code generated by "stringer -type=Role"; DO NOT EDIT.

package user

import "strconv"

const _Role_name = "AdministratorAuthorVisitorExpert"

var _Role_index = [...]uint8{0, 13, 19, 26, 32}

func (i Role) String() string {
	i -= 1
	if i < 0 || i >= Role(len(_Role_index)-1) {
		return "Role(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
